services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: rag-postgres

    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"