spring.application.name=PDF-RAG-project
spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.openai.api-key=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

spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.ollama.base-url=http://localhost:11434
app.file.upload-dir=uploads
